[project]
name = "ppl-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax[cuda12]>=0.5.0",
    "numpyro>=0.16.1",
    "pyro-ppl>=1.9.1",
    "torchvision>=0.21.0",
]
